### ISSUE TITLE
Journal Preparation

### ISSUE THREAD

**Issue by tgsiva** [tgsiva/ABAC#1]
- [x]  Prepare Journal

- [x]  Check Plagiarism

**Comment by Divya2805** [comment]
1.ABAC(HIBE-IKE) document work(pending)
2.Topics Finised(Plagiarism checked)
     -Abstract
     -Introduction
     -ABAC method
3. Contents need on the following topics
     -HIBE Encryption,Decription and Key Updation
     -Architecture Diagram

**Comment by Divya2805** [comment]
1) HIBE-IKE(ABAC) journal-completed(plagiarism checked)

**Comment by tgsiva** [comment]
Okay done....
